{% set name = "python-fasthtml" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-fasthtml-{{ version }}.tar.gz
  sha256: 978505e525ed79ff242bca11fee81b7bfca1c3f7506bd40b0eebbb80cdd5f34a

build:
  entry_points:
    - fh_railway_link=fasthtml.cli:railway_link
    - fh_railway_deploy=fasthtml.cli:railway_deploy
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - fastcore >=1.6.0
    - python-dateutil
    - starlette >0.33
    - oauthlib
    - itsdangerous
    - uvicorn >=0.30
    - httpx
    - fastlite >=0.0.6
    - python-multipart
    - beautifulsoup4

test:
  imports:
    - fasthtml
  commands:
    - pip check
    - fh_railway_link --help
    - fh_railway_deploy --help
  requires:
    - pip

about:
  home: https://github.com/AnswerDotAI/fasthtml
  summary: The fastest way to create an HTML app
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
