context:
  version: "0.14.13"

package:
  name: python-fasthtml
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/python-fasthtml/python_fasthtml-${{ version }}.tar.gz
  sha256: fbdef364d3824f5db2f40e0884b4541f00b2d7ec925e5e1e62949b2ede7daf5d


build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fh_railway_link=fasthtml.cli:railway_link
      - fh_railway_deploy=fasthtml.cli:railway_deploy

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - fastcore >=2.2.7
    - python-dateutil
    - starlette >=1.0.1
    - oauthlib
    - itsdangerous
    - python-multipart
    - beautifulsoup4
    - uvicorn >=0.30
    - httpx2
tests:
  - python:
      imports:
        - fasthtml
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - script:
      - fh_railway_link --help
      - fh_railway_deploy --help
    requirements:
      run:
        - python ${{ python_min }}.*


about:
  summary: The fastest way to create an HTML app
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/AnswerDotAI/fasthtml

extra:
  recipe-maintainers:
    - synapticarbors
