schema_version: 1

context:
  name: python-fasthtml
  version: 0.9.1
  python_min: "3.10" # remove this line once https://github.com/prefix-dev/rattler-build/pull/1122 is available

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 95fd510c7b71bee14b49d35d3367345c16c23df9eb23810c413c38f64eb61ae8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fh_railway_link=fasthtml.cli:railway_link
      - fh_railway_deploy=fasthtml.cli:railway_deploy

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - fastcore >=1.7.18
    - python-dateutil
    - starlette >0.33
    - oauthlib
    - itsdangerous
    - uvicorn >=0.30
    - httpx
    - fastlite >=0.0.9
    - python-multipart
    - beautifulsoup4

tests:
  - python:
      imports:
        - fasthtml
      pip_check: true
  - script:
      - fh_railway_link --help
      - fh_railway_deploy --help

about:
  summary: The fastest way to create an HTML app
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/AnswerDotAI/fasthtml

extra:
  recipe-maintainers:
    - synapticarbors

